# Generated by Django 3.1.13 on 2021-09-28 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210926_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 28)),
            preserve_default=False,
        ),
    ]
