# Generated by Django 3.1.13 on 2021-09-28 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_useraction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='date',
        ),
        migrations.AddField(
            model_name='useraction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
