# Generated by Django 3.1.13 on 2021-09-29 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210929_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 1, 12, 15, 678788)),
        ),
    ]
